# This is a basic workflow to help you get started with Actions

name: Github Action for LaTeX

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build_latex"
  build_latex:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: codebook.tex
          latexmk_use_xelatex: true
          latexmk_shell_escape: true

      # Push codebook.pdf to repo
      - uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo

      - name: Commit files
          run: |
            git config --local user.email "b07902047@ntu.edu.tw"
            git config --local user.name "robert1003"
            git commit -m "Add Codebook" -a
            
      - name: Push changes
        uses: robert1003/998244353@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
